export { FullConjugation } from './fullConjugation.js';

export { Aillir } from './aillir.js';
export { Aitre } from './aitre.js';
export { Aller } from './aller.js';
export { Asseoir } from './asseoir.js';
export { Avoir } from './avoir.js';
// export { Ayer } from './ayer.js';
// export { Battre } from './battre.js';
// export { Cevoir } from './cevoir.js';
// export { Clure } from './clure.js';
// export { Coudre } from './coudre.js';
// export { Courir } from './courir.js';
// export { Croire } from './croire.js';
// export { Cueillir } from './cueillir.js';
export { Devoir } from './devoir.js';
// export { Dire } from './dire.js';
// export { Dormir } from './dormir.js';
// export { Ecrire } from './ecrire.js';
// export { Eindre } from './eindre.js';
// export { Entir } from './entir.js';
export { Er } from './er.js';
// export { Erer } from './erer.js';
// export { Eter } from './eter.js';
export { Etre } from './etre.js';
// export { Faillir } from './faillir.js';
export { Faire } from './faire.js';
// export { Falloir } from './falloir.js';
// export { Fire } from './fire.js';
// export { Fuir } from './fuir.js';
// export { Hair } from './hair.js';
export { Ir } from './ir.js';
export { Lever } from './lever.js';
// export { Lire } from './lire.js';
// export { Mettre } from './mettre.js';
// export { Mourir } from './mourir.js';
// export { Naitre } from './naitre.js';
// export { Ndre } from './ndre.js';
// export { Oir } from './oir.js';
// export { Oire } from './oire.js';
// export { Ouillir } from './ouillir.js';
// export { Outre } from './outre.js';
// export { Plaire } from './plaire.js';
// export { Pouvoir } from './pouvoir.js';
// export { Ppeler } from './ppeler.js';
// export { Prendre } from './prendre.js';
// export { Querir } from './querir.js';
export { Re } from './re.js';
// export { Rir } from './rir.js';
// export { Rire } from './rire.js';
// export { Rtir } from './rtir.js';
// export { Savoir } from './savoir.js';
// export { Soudre } from './soudre.js';
// export { Suivre } from './suivre.js';
// export { Tenir } from './tenir.js';
// export { Uire } from './uire.js';
// export { Vaincre } from './vaincre.js';
// export { Valoir } from './valoir.js';
// export { Vetir } from './vetir.js';
// export { Vivre } from './vivre.js';
// export { Vouloir } from './vouloir.js';
