export { FullConjugation } from './fullConjugation';

export { Aillir } from './aillir';
export { Aitre } from './aitre';
export { Aller } from './aller';
export { Asseoir } from './asseoir';
export { Avoir } from './avoir';
// export { Ayer } from './ayer';
// export { Battre } from './battre';
// export { Cevoir } from './cevoir';
// export { Clure } from './clure';
// export { Coudre } from './coudre';
// export { Courir } from './courir';
// export { Croire } from './croire';
// export { Cueillir } from './cueillir';
export { Devoir } from './devoir';
// export { Dire } from './dire';
// export { Dormir } from './dormir';
// export { Ecrire } from './ecrire';
// export { Eindre } from './eindre';
// export { Entir } from './entir';
export { Er } from './er';
// export { Erer } from './erer';
// export { Eter } from './eter';
export { Etre } from './etre';
// export { Faillir } from './faillir';
export { Faire } from './faire';
// export { Falloir } from './falloir';
// export { Fire } from './fire';
// export { Fuir } from './fuir';
// export { Hair } from './hair';
export { Ir } from './ir';
export { Lever } from './lever';
// export { Lire } from './lire';
// export { Mettre } from './mettre';
// export { Mourir } from './mourir';
// export { Naitre } from './naitre';
// export { Ndre } from './ndre';
// export { Oir } from './oir';
// export { Oire } from './oire';
// export { Ouillir } from './ouillir';
// export { Outre } from './outre';
// export { Plaire } from './plaire';
// export { Pouvoir } from './pouvoir';
// export { Ppeler } from './ppeler';
// export { Prendre } from './prendre';
// export { Querir } from './querir';
export { Re } from './re';
// export { Rir } from './rir';
// export { Rire } from './rire';
// export { Rtir } from './rtir';
// export { Savoir } from './savoir';
// export { Soudre } from './soudre';
// export { Suivre } from './suivre';
// export { Tenir } from './tenir';
// export { Uire } from './uire';
// export { Vaincre } from './vaincre';
// export { Valoir } from './valoir';
// export { Vetir } from './vetir';
// export { Vivre } from './vivre';
// export { Vouloir } from './vouloir';
