export { Conditional } from './conditional.js';
export { Future } from './future.js';
export { FutureAnterior } from './futureAnterior.js';
export { Imperative } from './imperative.js';
export { Imperfect } from './imperfect.js';
export { ImperfectSubjunctive } from './imperfectSubjunctive.js';
export { Past } from './past.js';
export { PastAnterior } from './pastAnterior.js';
export { PastConditional } from './pastConditional.js';
export { PastSubjunctive } from './pastSubjunctive.js';
export { Pluperfect } from './pluperfect.js';
export { PluperfectSubjunctive } from './pluperfectSubjunctive.js';
export { Present } from './present.js';
export { SimplePast } from './simplePast.js';
export { Subjunctive } from './subjunctive.js';
export { Persons, Tense, TenseList } from './tense.js';
